package lexer;

public enum TokenType {
    CONST, VAR, TYPE, FUNC, IF, ELSE, FOR, RETURN, RANGE, MAP, INT_TYPE, FLOAT64_TYPE, STRING_TYPE,

    IDENT, INT_NUMBER, FLOAT_NUMBER, STRING,

    ASSIGN, COLON_ASSIGN,
    PLUS, MINUS, MULT, DIV, MOD,
    PLUS_ASSIGN, MINUS_ASSIGN, MULT_ASSIGN, DIV_ASSIGN, MOD_ASSIGN,
    INC, DEC,
    EQUALS, NEQ, LT, GT, LEQ, GEQ,
    AND_AND, OR_OR, NOT,

    SEMICOLON, COMMA, COLON, DOT,
    LPAR, RPAR, LBRACE, RBRACE, LBRACK, RBRACK,

    EOF
}
